title: Zaitang Li
description: Ph.D. Candidate in Computer Science and Engineering at CUHK
baseurl: ""
url: "https://lizaitang.github.io"
github_username: lizaitang

theme: minima

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
